version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - DATABASE_URL=sqlite:///./data.db
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install --silent && npm run dev -- --host"
    ports:
      - '5173:5173'
  # optional: add minio if you want S3 locally
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - '9000:9000'
